import {validateChart} from './core.js';
const $=id=>document.getElementById(id),audio=$('audio'),canvas=$('timeline'),ctx=canvas.getContext('2d');let chart,dirty=false,manifest=[];
const current=()=>chart.charts[$('level').value];
function message(t){$('message').textContent=t;}
function render(){current().sort((a,b)=>a.time-b.time);$('rows').replaceChildren();for(const n of current()){const row=document.createElement('tr'),td=document.createElement('td'),input=document.createElement('input');input.type='number';input.step='.005';input.min=0;input.max=chart.duration-.001;input.value=n.time;input.onchange=()=>{const v=Number(input.value);if(!Number.isFinite(v)||v<0||v>=chart.duration){input.value=n.time;message('時刻が区間の範囲外です');return;}n.time=v;dirty=true;render();};td.append(input);const laneCell=document.createElement('td'),select=document.createElement('select');for(let i=0;i<4;i++){const o=new Option('レーン '+(i+1),i);select.add(o);}select.value=n.lane;select.onchange=()=>{n.lane=Number(select.value);dirty=true;};laneCell.append(select);if(chart.stems){const part=document.createElement('select');for(const p of chart.stems.filter(p=>p.role==='playable'))part.add(new Option(p.id,p.id));part.value=n.part;part.onchange=()=>{n.part=part.value;dirty=true;};const duration=document.createElement('input');duration.type='number';duration.min='.001';duration.step='.005';duration.value=n.duration;duration.setAttribute('aria-label','発音する秒数');duration.onchange=()=>{const v=Number(duration.value);if(v>0&&n.time+v<=chart.duration){n.duration=v;dirty=true;}else duration.value=n.duration;};laneCell.append(part,duration);}const actions=document.createElement('td'),seek=document.createElement('button'),del=document.createElement('button');seek.textContent='聴く';seek.onclick=()=>{audio.currentTime=chart.clipStart+Math.max(0,n.time-1);audio.play().catch(e=>message(e.message));};del.textContent='削除';del.onclick=()=>{current().splice(current().indexOf(n),1);dirty=true;render();};actions.append(seek,del);row.append(td,laneCell,actions);$('rows').append(row);}message(`${current().length}ノーツ。変更後はJSONを書き出してください。`);}
async function load(){try{chart=validateChart(await(await fetch(manifest.find(t=>t.id===$('track').value)?.chart||$('track').value+'.json')).json());applyAudio();dirty=false;render();}catch(e){message(e.message)}}
function applyAudio(){audio.pause();audio.src=chart.stems?.find(p=>p.role==='playable')?.audio||chart.audio;audio.onloadedmetadata=()=>{audio.currentTime=chart.clipStart;};$('clipStart').value=chart.clipStart;$('duration').value=chart.duration;}
function add(lane=0){if(!chart)return;const t=audio.currentTime-chart.clipStart;if(t<0||t>=chart.duration){message('試遊区間の中で追加してください');return;}if(current().some(n=>n.lane===lane&&Math.abs(n.time-t)<.05))return;current().push({time:Math.round(t*1000)/1000,lane,...(chart.stems?{part:chart.stems.find(p=>p.role==='playable').id,duration:Math.min(.3,chart.duration-t)}:{})});dirty=true;render();}
$('track').onchange=load;$('level').onchange=render;$('add').onclick=()=>add();document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.repeat)return;const lane=['KeyD','KeyF','KeyJ','KeyK'].indexOf(e.code);if(lane>=0){e.preventDefault();add(lane);}});
$('apply').onclick=()=>{const shift=Number($('shift').value)/1000;if(!Number.isFinite(shift)||current().some(n=>n.time+shift<0||n.time+shift>=chart.duration)){message('ずらすと区間外になるノーツがあります');return;}for(const n of current())n.time=Math.round((n.time+shift)*1000)/1000;dirty=true;render();};
$('clipApply').onclick=()=>{const start=Number($('clipStart').value),duration=Number($('duration').value);if(!Number.isFinite(start)||start<0||!Number.isFinite(duration)||duration<=0||duration>900||start+duration>audio.duration||Object.values(chart.charts).some(ns=>ns.some(n=>n.time>=duration))){message('区間が音源を超えているか、範囲外のノーツがあります');return;}chart.clipStart=start;chart.duration=duration;audio.currentTime=start;dirty=true;render();};
function validated(){chart.analysis='Edited in Chart Workshop';return validateChart(chart);}
$('export').onclick=()=>{try{const blob=new Blob([JSON.stringify(validated(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=chart.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dirty=false;message('JSONを書き出しました。保存先を確認してください。');}catch(e){message(e.message)}};
$('try').onclick=()=>{try{sessionStorage.setItem('enzine-rythm-custom-chart',JSON.stringify(validated()));audio.pause();location.href='./?custom=1';}catch(e){message(e.message)}};
$('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>2000000)throw Error('JSONは2MB以下にしてください');chart=validateChart(JSON.parse(await f.text()));applyAudio();dirty=true;render();}catch(e){message('読み込めません：'+e.message)}};
canvas.onclick=e=>{if(!chart)return;const r=canvas.getBoundingClientRect();audio.currentTime=chart.clipStart+(e.clientX-r.left)/r.width*chart.duration;};
function draw(){ctx.fillStyle='#122017';ctx.fillRect(0,0,900,150);if(chart){const time=audio.currentTime-chart.clipStart;for(const n of current()){ctx.fillStyle=['#d8ec79','#cbbae8','#86d9c8','#f3b391'][n.lane];ctx.fillRect(n.time/chart.duration*900,n.lane*33+8,3,24);}ctx.fillStyle='#fff';ctx.fillRect(time/chart.duration*900,0,2,150);$('position').textContent=`区間内 ${Math.max(0,time).toFixed(2)} / ${chart.duration} 秒　音源内 ${audio.currentTime.toFixed(2)} 秒`;if(time>=chart.duration&&!audio.paused){audio.pause();audio.currentTime=chart.clipStart;}}requestAnimationFrame(draw);}try{manifest=await(await fetch('tracks.json')).json();$('track').replaceChildren();for(const t of manifest)$('track').add(new Option(t.subtitle,t.id));await load();draw();}catch(e){message(e.message);}


