import {DEFAULTS,WINDOWS,validateChart,nearestNote,grade,playableNotes,accuracy,keyLabel} from './core.js';
import {StemPlayer} from './stem-player.js';
const $=id=>document.getElementById(id), canvas=$('canvas'),x=canvas.getContext('2d');
const colors=['#d8ec79','#cbbae8','#86d9c8','#f3b391'];
let settings=structuredClone(DEFAULTS);try{const s=JSON.parse(localStorage.getItem('enzine-rythm-settings'));if(s&&Array.isArray(s.keys)&&s.keys.length===4&&new Set(s.keys).size===4&&s.keys.every(k=>typeof k==='string')&&typeof s.tapKey==='string')settings={...settings,...s};}catch{}
settings.offset=Math.max(-250,Math.min(250,Number(settings.offset)||0));settings.volume=Math.max(0,Math.min(1,Number(settings.volume)||0));
let tracks=[],selected=0,chart,context,gain,state='idle',startAt=0,notes=[],stats,score=0,combo=0,maxCombo=0,flashes=[],effects=[],capture=null,previousState='playing',best=0,raf;
let player,compressor;
const hitWindow=()=>chart?.stems?WINDOWS.relaxed:WINDOWS.good;
settings.drumVolume=Number.isFinite(Number(settings.drumVolume))?Math.max(0,Math.min(2,Number(settings.drumVolume))):DEFAULTS.drumVolume;
const clockText=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
const save=()=>{try{localStorage.setItem('enzine-rythm-settings',JSON.stringify(settings));}catch{}};
const elapsed=()=>context?context.currentTime-startAt:0;
const active=()=>state==='playing';
function pads(){const count=$('mode').value==='tap'?1:4;$('pads').replaceChildren();for(let i=0;i<count;i++){const b=document.createElement('button');b.style.setProperty('--color',colors[i]);b.textContent=count===1?'TAP / '+keyLabel(settings.tapKey):keyLabel(settings.keys[i]);b.setAttribute('aria-label',count===1?'リズムをタップ':'レーン'+(i+1));b.addEventListener('pointerdown',e=>{e.preventDefault();hit(i)});$('pads').append(b);}}
function info(){if(!chart)return;const ns=playableNotes(chart,$('difficulty').value,$('mode').value);$('trackInfo').textContent=`${clockText(Math.ceil(chart.duration))} / ${ns.length}ノーツ / ${chart.stems?"フル尺・ドラムを演奏":"テンポ推定 "+chart.estimatedBpm+" BPM"}`;$('status').textContent=chart.stems?'伴奏は常に流れます。許容範囲内なら押した瞬間にドラムが鳴ります。早押し・遅押しも音に反映します。':'光がラインに重なったらタップ。失敗しても最後まで遊べます。';pads();}
async function select(i){selected=i;chart=tracks[i].data;const hard=$('difficulty').querySelector('option[value="hard"]');hard.disabled=!chart.charts.hard;if(hard.disabled&&$('difficulty').value==='hard')$('difficulty').value='normal';document.querySelectorAll('.track').forEach((b,j)=>{b.classList.toggle('selected',i===j);b.setAttribute('aria-pressed',String(i===j));});info();}
async function audio(){context ||= new AudioContext({latencyHint:"interactive"});if(context.state==='suspended')await context.resume();gain ||= context.createGain();gain.gain.value=settings.volume;gain.disconnect();compressor ||= context.createDynamicsCompressor();compressor.threshold.value=-3;compressor.knee.value=3;compressor.ratio.value=12;compressor.attack.value=.003;compressor.release.value=.1;gain.connect(compressor);compressor.disconnect();compressor.connect(context.destination);}
function stop(){player?.stop();}
function setLocked(locked){$('quit').disabled=state==='loading';document.body.classList.toggle('playing',locked);$('mode').disabled=locked;$('difficulty').disabled=locked;document.querySelectorAll('.track').forEach(b=>b.disabled=locked);$('start').disabled=locked;}
async function start(){if(state==='loading'||active())return;state='loading';setLocked(true);$('status').textContent='音源を読み込み中…';$('result').hidden=true;
  try{await audio();player ||= new StemPlayer(context,gain);await player.load(chart);
    stop();notes=playableNotes(chart,$('difficulty').value,$('mode').value);stats={perfect:0,great:0,good:0,miss:0,empty:0};score=combo=maxCombo=0;flashes=[];effects=[];startAt=context.currentTime+2.2;player.setDrumVolume(settings.drumVolume);player.start(chart,startAt);state='playing';$('pause').disabled=false;$('pause').textContent='一時停止';$('overlay').hidden=true;$('judgment').textContent='READY';$('score').textContent='000000';$('combo').textContent='0';$('status').textContent=chart.title+' をプレイ中';canvas.scrollIntoView({block:'center',behavior:'smooth'});$('quit').disabled=false;if(document.hidden)await pause();
  }catch(e){stop();state='idle';setLocked(false);$('status').textContent='読み込めませんでした：'+e.message;$('overlay').hidden=false;}}
function se(lane){if(!settings.sfx||!context)return;const o=context.createOscillator(),g=context.createGain();o.frequency.value=[740,880,988,1175][lane];g.gain.setValueAtTime(.04*settings.volume,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.06);o.connect(g);g.connect(context.destination);o.start();o.stop(context.currentTime+.07);o.onended=()=>{o.disconnect();g.disconnect();};}
function hit(lane){if(!active()||elapsed()<0||$('settings').open)return;const now=elapsed();if(flashes[lane]&&now-flashes[lane]<.045)return;flashes[lane]=now;const match=nearestNote(notes,lane,now-settings.offset/1000,hitWindow());if(match){const kind=grade(match.delta);match.note.done=true;stats[kind]++;combo++;maxCombo=Math.max(maxCombo,combo);score+={perfect:1000,great:750,good:400}[kind];effects.push({lane,time:now,label:kind.toUpperCase(),color:colors[lane]});$('judgment').textContent=kind.toUpperCase()+(kind==='good'?(now-settings.offset/1000<match.note.time?' / 少し早い':' / 少し遅い'):'');if(chart.stems)player.hit(match.note);else se(lane);}else{stats.empty++;combo=0;score=Math.max(0,score-200);effects.push({lane,time:now,label:'BAD',color:'#ff7185'});$('judgment').textContent='BAD / 空振り';}hud();}
function hud(){$('score').textContent=String(score).padStart(6,'0');$('combo').textContent=combo;}
async function pause(){if(state==='playing'){previousState=state;state='paused';await context.suspend();$('pause').textContent='再開';$('overlay').hidden=false;$('overlay').innerHTML='<h2>PAUSED</h2><p>再開ボタンで続けられます。</p>';}else if(state==='paused'&&!$('settings').open){await context.resume();state=previousState;$('pause').textContent='一時停止';$('overlay').hidden=true;}}
function result(){stop();state='result';$('pause').disabled=true;const acc=accuracy(stats,notes.length),rank=acc>=95?'S':acc>=85?'A':acc>=70?'B':'C';const bestKey=`enzine-rythm-best:${chart.id}:${chart.chartRevision||"original"}:${$('mode').value}:${$('difficulty').value}`;try{best=Number(localStorage.getItem(bestKey))||0;if(score>best){best=score;localStorage.setItem(bestKey,best);}}catch{best=score;}$('rank').textContent=rank+' / '+acc.toFixed(1)+'%';$('resultText').textContent=`${score.toLocaleString()} 点 · BEST ${best.toLocaleString()}\nPERFECT ${stats.perfect} / GREAT ${stats.great}\nGOOD ${stats.good} / MISS ${stats.miss} / BAD ${stats.empty}\n最大コンボ ${maxCombo} / ${notes.length}`;$('result').hidden=false;$('judgment').textContent='NICE PLAY!';}
function menu(){stop();$('partStatus').textContent='READY';$('judgment').textContent='READY';$('time').textContent=clockText(Math.ceil(chart.duration));$('progress').style.width='0%';$('pause').textContent='一時停止';if(context?.state==='suspended')context.resume();state='idle';setLocked(false);$('result').hidden=true;$('overlay').hidden=false;$('overlay').innerHTML='<span class="disc-icon">♪</span><h2>ONE MORE TRACK?</h2><p>曲とあそび方を選んでください。</p>';$('pause').disabled=true;info();window.scrollTo({top:0,behavior:'smooth'});}
function draw(){const t=active()||state==='paused'?elapsed():0,count=$('mode').value==='tap'?1:4,w=480/count,target=475,travel=1.8;x.fillStyle='#101e17';x.fillRect(0,0,480,580);
  for(let i=0;i<count;i++){x.fillStyle=i%2?'#15241b':'#112018';x.fillRect(i*w,0,w,580);if(t-(flashes[i]??-99)<.14){x.fillStyle=colors[i]+'25';x.fillRect(i*w,0,w,580)}x.strokeStyle='#344631';x.beginPath();x.moveTo(i*w,0);x.lineTo(i*w,580);x.stroke();}
  for(let i=0;i<8;i++){let y=((i*90+t*100)%720+720)%720-90;x.strokeStyle='#203525';x.beginPath();x.moveTo(0,y);x.lineTo(480,y);x.stroke();}
  x.fillStyle='#cceaa40b';x.fillRect(0,target-22,480,44);x.strokeStyle='#dcf5a5';x.lineWidth=2;x.beginPath();x.moveTo(0,target);x.lineTo(480,target);x.stroke();
  for(let i=0;i<count;i++){x.strokeStyle=colors[i];x.lineWidth=2;x.beginPath();x.roundRect(i*w+12,target-16,w-24,32,8);x.stroke();}
  if(active()||state==='paused'){for(const n of notes){if(n.done)continue;const delta=n.time-(t-settings.offset/1000),y=target-delta/travel*target;if(active()&&delta< -hitWindow()){n.done=true;stats.miss++;combo=0;$('judgment').textContent='MISS';hud();continue;}if(y< -20||y>580)continue;x.fillStyle=colors[n.lane];x.shadowColor=colors[n.lane];x.shadowBlur=12;x.beginPath();x.roundRect(n.lane*w+16,y-10,w-32,20,7);x.fill();x.shadowBlur=0;x.fillStyle='#ffffff70';x.fillRect(n.lane*w+23,y-7,w-46,3);
      if(active()&&delta< -hitWindow()){n.done=true;stats.miss++;combo=0;$('judgment').textContent='MISS';hud();}}
    effects=effects.filter(e=>t-e.time<.6);for(const e of effects){let age=t-e.time;x.globalAlpha=1-age/.6;x.fillStyle=e.color;x.font='bold 16px sans-serif';x.textAlign='center';x.fillText(e.label,(e.lane+.5)*w,target-30-age*60);x.globalAlpha=1;}
    $('progress').style.width=Math.max(0,Math.min(100,t/chart.duration*100))+'%';$('time').textContent=clockText(Math.max(0,Math.ceil(chart.duration-t)));$('partStatus').textContent=chart.stems?(t<0?'伴奏 + ドラム / READY':player.audible('drums')?'伴奏 ♪ + ドラム ●':'伴奏 ♪ / ドラム ○'):'フルミックス再生';if(t<0){x.fillStyle='#e2efbc';x.font='bold 72px sans-serif';x.textAlign='center';x.fillText(Math.ceil(-t),240,270);}if(active()&&t>=chart.duration)result();}
  raf=requestAnimationFrame(draw);
}
function bindings(){ $('bindings').replaceChildren();[...settings.keys,settings.tapKey].forEach((code,i)=>{const b=document.createElement('button');b.textContent=(i===4?'1タップ':'レーン'+(i+1))+' : '+keyLabel(code);b.onclick=()=>{capture=i;$('bindingStatus').textContent='キーを入力してください。Escでキャンセル。';};$('bindings').append(b);});$('offset').value=settings.offset;$('offsetValue').textContent=settings.offset+' ms';$('volume').value=settings.volume;$('drumVolume').value=settings.drumVolume;$('drumVolumeValue').textContent=Math.round(settings.drumVolume*100)+'%';$('sfx').checked=settings.sfx;}
document.addEventListener('keydown',e=>{if(capture!==null){e.preventDefault();if(e.code==='Escape'){capture=null;$('bindingStatus').textContent='キャンセルしました';return;}if(e.ctrlKey||e.metaKey||e.altKey||['Tab','Enter'].includes(e.code)||/^(Shift|Control|Alt|Meta)/.test(e.code))return;if(capture<4&&settings.keys.some((k,i)=>i!==capture&&k===e.code)){$('bindingStatus').textContent='そのキーは別のレーンで使用中です';return;}if(capture===4)settings.tapKey=e.code;else settings.keys[capture]=e.code;capture=null;save();bindings();pads();$('bindingStatus').textContent='保存しました';return;}if($('settings').open||['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(e.target.tagName))return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)pause();return;}const lane=$('mode').value==='tap'?(e.code===settings.tapKey?0:-1):settings.keys.indexOf(e.code);if(lane>=0){e.preventDefault();if(!e.repeat)hit(lane);}});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();hit(Math.min(($('mode').value==='tap'?1:4)-1,Math.floor((e.clientX-r.left)/r.width*($('mode').value==='tap'?1:4))));});
$('start').onclick=()=>{document.activeElement.blur();start()};$('retry').onclick=()=>{document.activeElement.blur();start()};$('back').onclick=menu;$('quit').onclick=()=>{if(state!=='loading')menu();};$('pause').onclick=()=>{document.activeElement.blur();pause()};$('mode').onchange=info;$('difficulty').onchange=info;
$('settingsButton').onclick=async()=>{if(active())await pause();bindings();$('settings').showModal();};$('closeSettings').onclick=()=>{$('settings').close();capture=null;};$('settings').addEventListener('close',()=>capture=null);$('offset').oninput=()=>{settings.offset=Number($('offset').value);$('offsetValue').textContent=settings.offset+' ms';save();};$('volume').oninput=()=>{settings.volume=Number($('volume').value);if(gain)gain.gain.value=settings.volume;save();};$('drumVolume').oninput=()=>{settings.drumVolume=Number($('drumVolume').value);$('drumVolumeValue').textContent=Math.round(settings.drumVolume*100)+'%';player?.setDrumVolume(settings.drumVolume);save();};$('sfx').onchange=()=>{settings.sfx=$('sfx').checked;save();};$('resetSettings').onclick=()=>{settings=structuredClone(DEFAULTS);save();bindings();pads();player?.setDrumVolume(settings.drumVolume);if(gain)gain.gain.value=settings.volume;};document.addEventListener('visibilitychange',()=>{if(document.hidden&&active())pause();});
try{const manifest=await(await fetch('tracks.json')).json();for(const track of manifest){track.data=validateChart(await(await fetch(track.chart)).json());tracks.push(track);}const custom=sessionStorage.getItem('enzine-rythm-custom-chart');if(custom){try{tracks.push({id:'custom',data:validateChart(JSON.parse(custom)),subtitle:'エディターから試遊',icon:'✎'});}catch{sessionStorage.removeItem('enzine-rythm-custom-chart');}}
  for(const [i,tr] of tracks.entries()){const b=document.createElement('button');b.className='track';const art=document.createElement('span');art.className='art';art.textContent=tr.icon;const details=document.createElement('span'),title=document.createElement('b'),sub=document.createElement('small');title.textContent=tr.data.title;sub.textContent=tr.subtitle;details.append(title,sub);const end=document.createElement('span');end.textContent='PLAY';b.append(art,details,end);b.onclick=()=>select(i);$('trackList').append(b);}
  if(new URLSearchParams(location.search).get('mode')==='lanes')$('mode').value='lanes';await select(new URLSearchParams(location.search).has('custom')?tracks.length-1:Math.max(0,tracks.findIndex(t=>t.id===new URLSearchParams(location.search).get('track'))));draw();
}catch(e){$('status').textContent='曲を読み込めません：'+e.message;$('start').disabled=true;}

