// Adapter for the isolated legacy samples. Pauses their timers and normalizes frame-based games to 60 Hz.
(()=>{'use strict';const config=window.GAME_CONFIG,realRAF=window.requestAnimationFrame.bind(window),realNow=Date.now.bind(Date),rafJobs=new Map(),timers=new Map();let id=0,paused=false,time=performance.now(),last=time,accumulator=0,capture=null,roundPractice=false,keys=config.controls.map(c=>c.code),audio;
 try{const stored=JSON.parse(localStorage.getItem('miitan-controls-'+config.id));if(Array.isArray(stored)&&stored.length===keys.length&&stored.every(k=>typeof k==='string')&&new Set(stored).size===stored.length)keys=stored;}catch{}
 const epoch=realNow()-time;window.GameShell={height:()=>Math.max(220,innerHeight-110),now:()=>epoch+time,beginRound:()=>{timers.clear();release();roundPractice=!!document.getElementById('practice')?.checked;},isDown:code=>[...held.values()].some(i=>config.controls[i]?.code===code),practice:()=>roundPractice};
 const clock={requestAnimationFrame:fn=>{const n=++id;rafJobs.set(n,fn);return n;},cancelAnimationFrame:n=>rafJobs.delete(n),setTimeout:(fn,delay=0,...args)=>{const n=++id;timers.set(n,{fn,args,due:time+Math.max(0,Number(delay)||0),interval:0});return n;},setInterval:(fn,delay=0,...args)=>{const n=++id;timers.set(n,{fn,args,due:time+Math.max(1,Number(delay)||1),interval:Math.max(1,Number(delay)||1)});return n;},clearTimeout:n=>timers.delete(n),clearInterval:n=>timers.delete(n)};
 GameShell.clock=clock;
 GameShell.run=game=>{GameShell.game=game;let previous=null;function tick(t){game.update(previous===null?0:(t-previous)/1000);previous=t;game.render();clock.requestAnimationFrame(tick);}clock.requestAnimationFrame(tick);};
 let effectsEnabled=false,effectsContext;GameShell.feedback=success=>{if(!effectsEnabled||paused)return;try{effectsContext ||= new (window.AudioContext||window.webkitAudioContext)();effectsContext.resume().catch(()=>{});const osc=effectsContext.createOscillator(),gain=effectsContext.createGain();osc.frequency.value=success?660:180;gain.gain.setValueAtTime(.025,effectsContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,effectsContext.currentTime+.12);osc.connect(gain).connect(effectsContext.destination);osc.start();osc.stop(effectsContext.currentTime+.12);}catch{}};
 document.addEventListener('shell-ready',()=>{const dialog=document.getElementById('shell-dialog');const block=document.createElement('section');block.innerHTML='<label><input id="shell-effects" type="checkbox"> 効果音（小さな音量 / BGMと別）</label><details><summary>この端末だけの試遊メモ</summary><label>初回プレイ秒数 <input id="play-seconds" type="number" min="0"></label><label>初クリアまでの回数 <input id="play-tries" type="number" min="0"></label><label>終了理由・遊びやすさ <textarea id="play-note" maxlength="2000"></textarea></label><button id="save-play-note">この端末に保存</button><p id="note-status" role="status"></p></details>';dialog.append(block);document.getElementById('shell-effects').onchange=e=>effectsEnabled=e.target.checked;const noteKey='collection04-v4-playnote-'+config.id;try{const n=JSON.parse(localStorage.getItem(noteKey));if(n){document.getElementById('play-seconds').value=n.seconds;document.getElementById('play-tries').value=n.tries;document.getElementById('play-note').value=n.note;}}catch{}document.getElementById('save-play-note').onclick=()=>{try{localStorage.setItem(noteKey,JSON.stringify({version:4,seconds:document.getElementById('play-seconds').value,tries:document.getElementById('play-tries').value,note:document.getElementById('play-note').value}));document.getElementById('note-status').textContent='このブラウザだけに保存しました（送信なし）';}catch{document.getElementById('note-status').textContent='保存できませんでした。メモを手元にコピーしてください';}};});
 // Migrated games receive this clock explicitly; legacy pages retain the adapter.
 if(!config.explicitClock)Object.assign(window,clock);
 GameShell.drag=(canvas,handlers)=>{let active=null,lastX=0;canvas.style.touchAction='none';const cancel=()=>{active=null;handlers.end?.();};canvas.addEventListener('pointerdown',e=>{if(active!==null||!e.isPrimary)return;e.preventDefault();active=e.pointerId;lastX=e.clientX;canvas.setPointerCapture(active);handlers.start?.(e);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==active)return;const dx=e.clientX-lastX;lastX=e.clientX;handlers.move?.(dx,e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(e.pointerId===active)cancel();});window.addEventListener('blur',cancel);window.addEventListener('resize',cancel);document.addEventListener('gamepause',cancel);};
 function step(delta){time+=delta;for(const [key,r] of repeats){if(time>=r.next){r.next=time+100;emit(r.i,'keydown');}}for(const [n,t] of [...timers]){if(t.due>time||!timers.has(n))continue;if(t.interval)t.due=time+t.interval;else timers.delete(n);try{if(typeof t.fn==='function')t.fn(...t.args);}catch(e){console.error(e);}}const jobs=[...rafJobs];rafJobs.clear();for(const [,fn]of jobs)try{fn(time);}catch(e){console.error(e);}}
 function frame(now){const dt=Math.min(100,now-last);last=now;if(!paused){if(config.fixed60){accumulator+=dt;let loops=0;while(accumulator>=1000/60&&loops++<6){step(1000/60);accumulator-=1000/60;}}else step(dt);}realRAF(frame);}realRAF(frame);
 const synthetic=new WeakSet(),held=new Map(),repeats=new Map();
 function emit(i,type){const c=config.controls[i];if(!c)return;if(c.selector){if(type==='keydown')document.querySelector(c.selector)?.click();return;}if(c.choice!==undefined){if(type==='keydown'){const options=[...document.querySelectorAll(config.choice)].filter(el=>el.getClientRects().length&&!el.disabled);options[c.choice]?.click();}return;}const ev=new KeyboardEvent(type,{code:c.code,key:c.key,bubbles:true,cancelable:true});synthetic.add(ev);document.dispatchEvent(ev);}
 function repeat(key,i){const c=config.controls[i];if(/^Arrow/.test(c.code)&&!['shooting','jump','dash','flick'].includes(config.id)&&!(config.id==='tetris'&&c.code==='ArrowUp'))repeats.set(key,{i,next:time+260});}
 function release(){repeats.clear();for(const i of held.values())emit(i,'keyup');held.clear();}
 function toggle(force){document.dispatchEvent(new Event('gamepause'));paused=typeof force==='boolean'?force:!paused;release();document.getElementById('shell-pause').hidden=!paused;for(const el of document.body.children){if(!['game-shell','shell-pause','shell-dialog'].includes(el.id)&&!['SCRIPT','LINK'].includes(el.tagName))el.inert=paused;}document.getElementById('shell-pause-button').textContent=paused?'再開':'一時停止';if(audio){if(paused)audio.pause();else if(audio.dataset.enabled==='yes')audio.play().catch(()=>{});}}
 GameShell.pause=force=>toggle(force);
 document.addEventListener('keydown',e=>{if(synthetic.has(e))return;if(capture!==null){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Escape'){capture=null;renderKeys();return;}if(e.ctrlKey||e.metaKey||e.altKey||['Tab','Enter'].includes(e.code)||/^(Shift|Control|Alt|Meta)/.test(e.code))return;if(keys.some((k,i)=>k===e.code&&i!==capture)){document.getElementById('shell-note').textContent='そのキーは使用中です';return;}keys[capture]=e.code;try{localStorage.setItem('miitan-controls-'+config.id,JSON.stringify(keys));}catch{}capture=null;renderKeys();renderPads();return;}if(document.getElementById('shell-dialog')?.open){e.stopImmediatePropagation();return;}if(paused){e.stopImmediatePropagation();if(e.code==='Escape'&&!e.repeat)toggle(false);return;}if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.target.closest('#game-shell')||e.target.closest('#shell-pads')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();toggle(true);return;}const i=keys.indexOf(e.code);if(i>=0){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat){held.set(e.code,i);emit(i,'keydown');repeat(e.code,i);}}else if(config.controls.some(c=>c.code===e.code)){e.preventDefault();e.stopImmediatePropagation();}},true);
 document.addEventListener('keyup',e=>{if(synthetic.has(e))return;const i=held.get(e.code);if(i!==undefined){e.preventDefault();e.stopImmediatePropagation();emit(i,'keyup');held.delete(e.code);repeats.delete(e.code);}},true);
 window.addEventListener('blur',()=>{release();if(document.getElementById('shell-pause'))toggle(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&document.getElementById('shell-pause'))toggle(true);});
 for(const type of ['pointerdown','pointermove','pointerup','mousedown','mousemove','mouseup','touchstart','touchmove','touchend','click'])document.addEventListener(type,e=>{if(paused&&!e.target.closest?.('#game-shell,#shell-pause,#shell-dialog')){e.preventDefault();e.stopImmediatePropagation();}},{capture:true,passive:false});
 function label(code){return code.replace('Key','').replace('Digit','').replace('Arrow','').replace('Space','SPACE');}
 function renderKeys(){const root=document.getElementById('shell-keys');root.replaceChildren();config.controls.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.label+' : '+label(keys[i]);b.onclick=()=>{capture=i;document.getElementById('shell-note').textContent='割り当てるキーを押してください（Escで取消）';};root.append(b);});document.getElementById('shell-note').textContent=keys.length?'設定はこのブラウザに保存されます。':'各ボタンはTabで選び、Enterで操作できます。';}
 function renderPads(){const root=document.getElementById('shell-pads');root.replaceChildren();config.controls.filter(c=>c.choice===undefined).forEach(c=>{const i=config.controls.indexOf(c),b=document.createElement('button');b.textContent=c.label+' '+label(keys[i]);b.onpointerdown=e=>{e.preventDefault();if(paused)return;b.setPointerCapture(e.pointerId);held.set('pointer:'+e.pointerId,i);emit(i,'keydown');repeat('pointer:'+e.pointerId,i);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=e=>{const key='pointer:'+e.pointerId;if(!held.has(key))return;held.delete(key);repeats.delete(key);if(![...held.values()].includes(i))emit(i,'keyup');};root.append(b);});if(!root.children.length)root.textContent='タップで選択 · Tab / Enterでも操作';root.style.color='#c1cfb6';root.style.fontSize='11px';root.style.alignItems='center';}
 document.addEventListener('keydown',e=>{if(!e.target.matches?.('.cell,.card,.choice,.emoji-cell')||!e.code.startsWith('Arrow')||paused)return;const cells=[...e.target.parentElement.children].filter(el=>el.matches('[tabindex]'));let i=cells.indexOf(e.target),cols=getComputedStyle(e.target.parentElement).gridTemplateColumns.split(' ').length;const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-cols,ArrowDown:cols}[e.code];if(i>=0&&cells[i+d]){e.preventDefault();cells[i+d].focus();}});
 document.addEventListener('DOMContentLoaded',()=>{const bar=document.createElement('nav');bar.id='game-shell';bar.innerHTML='<a href="../../">← 一覧</a><button id="shell-pause-button">一時停止</button><button id="shell-music">BGM OFF</button><button id="shell-settings">操作設定</button>';document.body.append(bar);const pads=document.createElement('div');pads.id='shell-pads';document.body.append(pads);const overlay=document.createElement('div');overlay.id='shell-pause';overlay.hidden=true;overlay.innerHTML='<p>ひとやすみ。</p><button id="shell-resume">ゲームに戻る</button>';document.body.append(overlay);const dialog=document.createElement('dialog');dialog.id='shell-dialog';dialog.innerHTML='<h2>操作設定</h2><p>変更したい操作を選び、好きなキーを押してください。</p><div id="shell-keys"></div><p id="shell-note"></p><button id="shell-reset">初期設定</button> <button id="shell-close">閉じる</button>';document.body.append(dialog);document.getElementById('shell-pause-button').onclick=()=>toggle();document.getElementById('shell-resume').onclick=()=>toggle(false);document.getElementById('shell-settings').onclick=()=>{toggle(true);renderKeys();dialog.showModal();};document.getElementById('shell-close').onclick=()=>dialog.close();dialog.onclose=()=>capture=null;document.getElementById('shell-reset').onclick=()=>{keys=config.controls.map(c=>c.code);try{localStorage.removeItem('miitan-controls-'+config.id);}catch{}renderKeys();renderPads();};document.getElementById('shell-music').onclick=async()=>{audio ||= new Audio('../../assets/bgm/arcade.mp3');audio.loop=true;audio.volume=.22;if(audio.dataset.enabled==='yes'){audio.pause();audio.dataset.enabled='no';}else{audio.dataset.enabled='yes';if(!paused)try{await audio.play();}catch{audio.dataset.enabled='no';}}document.getElementById('shell-music').textContent='BGM '+(audio.dataset.enabled==='yes'?'ON':'OFF');};renderPads();document.dispatchEvent(new Event('shell-ready'));
   const decorate=()=>{document.querySelectorAll('.card,.cell,.choice,#rowB .emoji-cell').forEach(el=>{if(el.tagName==='BUTTON'||el.hasAttribute('tabindex')||el.classList.contains('given'))return;el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.code==='Enter'&&!e.repeat){e.preventDefault();el.click();}});});};decorate();new MutationObserver(decorate).observe(document.body,{subtree:true,childList:true});
 });
})();


